Repository southworks/botbuilder-java, pull requests merged in 2021-03, with the labels that each got.

#78 Add DialogBot class and POM
  samples/13.core-bot/pom.xml
  samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/DialogBot.java
  samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/package-info.java
Labels: PR: reviewed approved

#83 [Samples][13.core-bot] Add cards
  samples/13.core-bot/src/main/resources/cards/welcomeCard.json
Labels: PR: reviewed approved

#81 [SDK][Bot-Azure] Implements AzureQueueStorage
  libraries/bot-azure/src/main/java/com/microsoft/bot/azure/queues/AzureQueueStorage.java
  libraries/bot-builder/pom.xml
  libraries/bot-builder/src/main/java/com/microsoft/bot/builder/QueueStorage.java
Labels: PR: reviewed approved

#82 [Samples][13.core-bot] Add deployment templates
  samples/13.core-bot/deploymentTemplates/template-with-new-rg.json
  samples/13.core-bot/deploymentTemplates/template-with-preexisting-rg.json
Labels: PR: reviewed approved

#80 [SDK][Bot-Azure] Add AzureQueueTests
  libraries/bot-azure/pom.xml
  libraries/bot-azure/src/test/java/com/microsoft/bot/azure/AzureQueueTests.java
  libraries/bot-builder/pom.xml
  libraries/bot-schema/src/main/java/com/microsoft/bot/schema/ActivityEventNames.java
Labels: PR: reviewed approved

#84 [Samples][13.core-bot] Add webapp folder
  samples/13.core-bot/src/main/webapp/META-INF/MANIFEST.MF
  samples/13.core-bot/src/main/webapp/WEB-INF/web.xml
  samples/13.core-bot/src/main/webapp/index.html
Labels: PR: reviewed approved

#86 Add CancelAndHelpDialog class
  samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/CancelAndHelpDialog.java
Labels: PR: reviewed approved

#88 [Samples][13.core-bot] Add cognitiveModels
  samples/13.core-bot/cognitiveModels/FlightBooking.json
Labels: PR: reviewed approved

#85 [Samples][Core-Bot] Add READMEs
  samples/13.core-bot/README-LUIS.md
  samples/13.core-bot/README.md
  samples/13.core-bot/pom.xml
Labels: PR: reviewed approved

#89 [Samples][Core-Bot] Add BookingDetails and FlightBookingRecognizer
  samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/BookingDetails.java
  samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/FlightBookingRecognizer.java
Labels: PR: reviewed approved

#90 [Samples][Core-Bot] Add MainDialog class
  samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/Application.java
  samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/BookingDialog.java
  samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/FlightBookingRecognizer.java
  samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/MainDialog.java
Labels: PR: reviewed approved

#92 [Samples][13.core-bot] Add DialogAndWelcomeBot
  samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/DialogAndWelcomeBot.java
Labels: PR: reviewed approved

#91 [Samples][13.core-bot] Add BookingDialog and DateResolver classes
  samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/BookingDialog.java
  samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/DateResolverDialog.java
Labels: PR: reviewed approved

#96 Add main structure
  samples/25.message-reaction/deploymentTemplates/template-with-new-rg.json
  samples/25.message-reaction/pom.xml
  samples/25.message-reaction/src/main/java/com/microsoft/bot/sample/messagereaction/Application.java
  samples/25.message-reaction/src/main/resources/application.properties
  samples/25.message-reaction/src/main/webapp/index.html
  samples/25.message-reaction/src/test/java/com/microsoft/bot/sample/messagereaction/ApplicationTest.java
Labels: PR: reviewed approved

#97 Add deployment templates to deploymentTemplates folder
  samples/25.message-reaction/deploymentTemplates/template-with-new-rg.json
  samples/25.message-reaction/deploymentTemplates/template-with-preexisting-rg.json
Labels: PR: reviewed approved

#98 [Samples][25.message-reaction] Migrate Properties folder
  samples/25.message-reaction/src/main/resources/application.properties
Labels: PR: reviewed approved

#100 [Samples][25.message-reaction] Add webapp
  samples/25.message-reaction/src/main/webapp/META-INF/MANIFEST.MF
  samples/25.message-reaction/src/main/webapp/WEB-INF/web.xml
  samples/25.message-reaction/src/main/webapp/index.html
Labels: PR: reviewed approved

#99 Add Application class
  samples/25.message-reaction/src/main/java/com/microsoft/bot/sample/messagereaction/Application.java
Labels: PR: reviewed approved

#101 Add values from appsettings.json
  samples/25.message-reaction/src/main/resources/application.properties
Labels: PR: reviewed approved

#102 Add teams manifest folder and files
  samples/25.message-reaction/teamsAppManifest/icon-color.png
  samples/25.message-reaction/teamsAppManifest/icon-outline.png
  samples/25.message-reaction/teamsAppManifest/manifest.json
Labels: PR: reviewed approved

#104 Add readme file
  samples/25.message-reaction/README.md
Labels: PR: reviewed approved

#108 [Samples][25.message-reaction] Add activityLog class
  samples/25.message-reaction/src/main/java/com/microsoft/bot/sample/messagereaction/ActivityLog.java
Labels: PR: reviewed approved

#103 [SDK] [Bot Azure] BlobsTranscriptStore
  libraries/bot-azure/pom.xml
  libraries/bot-azure/src/main/java/com/microsoft/bot/azure/blobs/BlobsTranscriptStore.java
Labels: PR: reviewed approved

#105 [SDK][Bot Azure] Migrate blobs transcript store tests
  libraries/bot-azure/src/test/java/com/microsoft/bot/azure/TranscriptStoreTests.java
Labels: PR: reviewed approved

#106 [SDK][Bot Azure] Create BlobsStorage
  libraries/bot-azure/src/main/java/com/microsoft/bot/azure/blobs/BlobsStorage.java
  libraries/bot-azure/src/test/java/com/microsoft/bot/azure/TranscriptStoreTests.java
  libraries/bot-azure/src/test/java/com/microsoft/bot/azure/blobs/BlobsStorageTests.java
  libraries/bot-builder/src/test/java/com/microsoft/bot/builder/StorageBaseTests.java
  libraries/bot-builder/src/test/java/com/microsoft/bot/builder/TestPocoState.java
Labels: PR: reviewed approved

#111 [SDK] [bot-applicationinsights] Create main structure
  libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/BotTelemetryClient.java
  libraries/bot-applicationinsights/src/test/java/com/microsoft/bot/applicationinsights/BotTelemetryClientTests.java
  libraries/bot-applicationinsights/src/test/java/com/microsoft/bot/applicationinsights/MyBotTelemetryClient.java
  libraries/bot-applicationinsights/src/test/java/com/microsoft/bot/applicationinsights/TelemetryWaterfallTests.java
Labels: PR: reviewed approved

#113 [SDK app-insights] Add TelemetryInitializerMiddleware class
  libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/core/TelemetryInitializerMiddleware.java
  libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/core/package-info.java
Labels: PR: reviewed approved

#116 [SDK][app-insights] Add BotTelemetryClient
  libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/AvailabilityTelemetry.java
  libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/BotTelemetryClient.java
  libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/BotTelemetryClientImpl.java
  libraries/bot-builder/pom.xml
  libraries/bot-builder/src/main/java/com/microsoft/bot/builder/BotTelemetryClient.java
  libraries/bot-builder/src/main/java/com/microsoft/bot/builder/NullBotTelemetryClient.java
  libraries/bot-builder/src/main/java/com/microsoft/bot/builder/Severity.java
  libraries/bot-dialogs/src/main/java/com/microsoft/bot/dialogs/DialogContainer.java
  libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/ComponentDialogTests.java
  libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/DialogSetTests.java
  libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/WaterfallTests.java
Labels: PR: reviewed approved

#114 [SDK][Application-Insights] Add MyBotTelemetryClient class
  libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/BotTelemetryClientImpl.java
  libraries/bot-applicationinsights/src/test/java/com/microsoft/bot/applicationinsights/MyBotTelemetryClient.java
  libraries/bot-builder/pom.xml
  libraries/bot-builder/src/main/java/com/microsoft/bot/builder/BotTelemetryClient.java
  libraries/bot-builder/src/main/java/com/microsoft/bot/builder/NullBotTelemetryClient.java
  libraries/bot-builder/src/main/java/com/microsoft/bot/builder/Severity.java
  libraries/bot-dialogs/src/main/java/com/microsoft/bot/dialogs/DialogContainer.java
  libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/ComponentDialogTests.java
  libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/DialogSetTests.java
  libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/WaterfallTests.java
Labels: PR: reviewed approved

#119 [SDK][BlobsStorage] Fix BlobsTranscriptStore class & unit tests
  libraries/bot-azure/src/main/java/com/microsoft/bot/azure/blobs/BlobsTranscriptStore.java
  libraries/bot-azure/src/test/java/com/microsoft/bot/azure/TranscriptStoreTests.java
  libraries/bot-azure/src/test/java/com/microsoft/bot/azure/blobs/BlobsStorageTests.java
  libraries/bot-builder/src/test/java/com/microsoft/bot/builder/TranscriptMiddlewareTest.java
  libraries/bot-schema/src/main/java/com/microsoft/bot/schema/Activity.java
  libraries/bot-schema/src/main/java/com/microsoft/bot/schema/NanoClockHelper.java
Labels: PR: reviewed approved

#118 [SDK][BlobsStorage]Fix BlobsStorage class & unit tests
  libraries/bot-azure/src/main/java/com/microsoft/bot/azure/blobs/BlobsStorage.java
  libraries/bot-azure/src/test/java/com/microsoft/bot/azure/blobs/BlobsStorageTests.java
Labels: PR: changes requested

#117 [SDK][ApplicationInsights] Implement tests
  libraries/bot-applicationinsights/src/test/java/com/microsoft/bot/applicationinsights/TelemetryWaterfallTests.java
  libraries/bot-dialogs/src/main/java/com/microsoft/bot/dialogs/WaterfallDialog.java
Labels: PR: reviewed approved

#120 [SDK][Application-Insights] Telemetry Initializer Tests
  libraries/bot-applicationinsights/pom.xml
  libraries/bot-applicationinsights/src/test/java/com/microsoft/bot/applicationinsights/TelemetryInitializerTests.java
Labels: PR: reviewed approved

#122 [SDK][app-insights] Add BotTelemetryClientTests
  libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/BotTelemetryClientImpl.java
  libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/core/TelemetryInitializerMiddleware.java
  libraries/bot-applicationinsights/src/test/java/com/microsoft/bot/applicationinsights/BotTelemetryClientTests.java
Labels: PR: reviewed approved

#126 [SDK][Bot-Azure] Replace assertEmulator with runIfEmulator
  libraries/bot-azure/src/test/java/com/microsoft/bot/azure/blobs/BlobsStorageTests.java
Labels: PR: reviewed approved

#127 [SDK][Luis] Remove double brace in bot-ai-luis-v3 library code + test
  libraries/bot-ai-luis-v3/src/main/java/com/microsoft/bot/ai/luis/LuisRecognizerOptionsV3.java
  libraries/bot-ai-luis-v3/src/test/java/com/microsoft/bot/ai/luis/LuisRecognizerOptionsV3Tests.java
  libraries/bot-ai-luis-v3/src/test/java/com/microsoft/bot/ai/luis/LuisRecognizerTests.java
Labels: PR: review wanted

#128 [Double Brace] Remove double braces in bot-ai-qna
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerRecognizer.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/GenerateAnswerUtils.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/QnACardBuilder.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerRecognizerTests.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTests.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTraceInfoTests.java
Labels: PR: reviewed approved

#132 [SDK][Bot-Integration-Core] Remove double brace in bot-integration-core library code + test
  libraries/bot-integration-core/src/main/java/com/microsoft/bot/integration/AdapterWithErrorHandler.java
Labels: PR: reviewed approved

#135 [SDK][Bot-Connector] Remove double brace initializations in code + unit tests
  libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/ChannelValidation.java
  libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/EmulatorValidation.java
  libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/EnterpriseChannelValidation.java
  libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/GovernmentChannelValidation.java
  libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/RetryParams.java
  libraries/bot-connector/src/test/java/com/microsoft/bot/connector/AllowedCallersClaimsValidationTests.java
  libraries/bot-connector/src/test/java/com/microsoft/bot/connector/AttachmentsTest.java
  libraries/bot-connector/src/test/java/com/microsoft/bot/connector/ConversationsTest.java
  libraries/bot-connector/src/test/java/com/microsoft/bot/connector/JwtTokenExtractorTests.java
  libraries/bot-connector/src/test/java/com/microsoft/bot/connector/JwtTokenValidationTests.java
  libraries/bot-connector/src/test/java/com/microsoft/bot/connector/RetryTests.java
Labels: PR: reviewed approved

#139 [Double Brace] Fix standard approach in the samples solution
  samples/03.welcome-user/src/main/java/com/microsoft/bot/sample/welcomeuser/WelcomeUserBot.java
  samples/06.using-cards/src/main/java/com/microsoft/bot/sample/usingcards/Cards.java
  samples/08.suggested-actions/src/main/java/com/microsoft/bot/sample/suggestedactions/SuggestedActionsBot.java
  samples/15.handling-attachments/src/main/java/com/microsoft/bot/sample/attachments/AttachmentsBot.java
  samples/50.teams-messaging-extensions-search/src/main/java/com/microsoft/bot/sample/teamssearch/TeamsMessagingExtensionsSearchBot.java
  samples/51.teams-messaging-extensions-action/src/main/java/com/microsoft/bot/sample/teamsaction/TeamsMessagingExtensionsActionBot.java
  samples/52.teams-messaging-extensions-search-auth-config/src/main/java/com/microsoft/bot/sample/teamssearchauth/TeamsMessagingExtensionsSearchAuthConfigBot.java
  samples/54.teams-task-module/src/main/java/com/microsoft/bot/sample/teamstaskmodule/TeamsTaskModuleBot.java
  samples/54.teams-task-module/src/main/java/com/microsoft/bot/sample/teamstaskmodule/models/TaskModuleResponseFactory.java
  samples/57.teams-conversation-bot/src/main/java/com/microsoft/bot/sample/teamsconversation/TeamsConversationBot.java
  samples/81.skills-skilldialog/dialog-root-bot/src/main/java/com/microsoft/bot/sample/dialogrootbot/Bots/RootBot.java
Labels: PR: reviewed approved

#141 [BotBuilder-Dialogs] - Remove DBI
  libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/choices/ChoiceFactoryTests.java
Labels: PR: reviewed approved

#142 [Double Brace][Connector] Add missing DBI in connector
  libraries/bot-connector/src/test/java/com/microsoft/bot/connector/JwtTokenValidationTests.java
Labels: PR: reviewed approved

#143 [QnA] Remove DBI in QnAMakerTests
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTests.java
Labels: PR: reviewed approved

#146 [Samples] Add main structure for sample 21 corebot app insights
  samples/21.core-bot-app-insights/pom.xml
  samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/Application.java
  samples/21.core-bot-app-insights/src/main/resources/cards/welcomeCard.json
  samples/21.core-bot-app-insights/src/main/webapp/index.html
  samples/21.core-bot-app-insights/src/test/java/com/microsoft/bot/sample/corebot/app/insights/ApplicationTest.java
Labels: PR: reviewed approved

#147 [Samples][21.corebot-app-insights] Copy cards folder
  samples/21.core-bot-app-insights/src/main/resources/cards/welcomeCard.json
Labels: PR: reviewed approved

#148 [Samples][Corebot-Application-Insights] Add application.properties file
  samples/21.core-bot-app-insights/src/main/resources/application.properties
Labels: PR: reviewed approved

#149 [Samples][21.corebot-app-insights] Migrate DialogAndWelcomeBot class
  samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/DialogAndWelcomeBot.java
Labels: PR: reviewed approved

#151 [Samples][21.corebot-app-insights] Migrate wwwroot folder
  samples/21.core-bot-app-insights/src/main/webapp/META-INF/MANIFEST.MF
  samples/21.core-bot-app-insights/src/main/webapp/WEB-INF/web.xml
  samples/21.core-bot-app-insights/src/main/webapp/index.html
Labels: PR: reviewed approved

#150 [Samples][21.corebot-app-insights] Migrate READMEs documents
  samples/21.core-bot-app-insights/README-LUIS.md
  samples/21.core-bot-app-insights/README.md
Labels: PR: reviewed approved

#152 [Samples][CoreBot-App-Insights] Add MainDialog class
  samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/MainDialog.java
Labels: PR: reviewed approved

#153 [Samples][Corebot-App-Insights] Add BookingDetails class
  samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/BookingDetails.java
Labels: PR: reviewed approved

#154 [Samples][nlp-with-dispatch] Create main structure
  samples/14.nlp-with-dispatch/LICENSE
  samples/14.nlp-with-dispatch/cognitiveModels/HomeAutomation.json
  samples/14.nlp-with-dispatch/deploymentTemplates/template-with-new-rg.json
  samples/14.nlp-with-dispatch/pom.xml
  samples/14.nlp-with-dispatch/src/main/java/com/microsoft/bot/sample/nlp/with/dispatch/Application.java
  samples/14.nlp-with-dispatch/src/main/resources/application.properties
  samples/14.nlp-with-dispatch/src/main/webapp/META-INF/MANIFEST.MF
  samples/14.nlp-with-dispatch/src/main/webapp/WEB-INF/web.xml
  samples/14.nlp-with-dispatch/src/test/java/com/microsoft/bot/sample/nlp/with/dispatch/ApplicationTest.java
Labels: PR: changes requested

#156 [Samples][21.corebot-app-insights] Migrate cognitiveModels folder
  samples/21.core-bot-app-insights/cognitiveModels/flightbooking.json
Labels: PR: reviewed approved

#157 [Samples][21.corebot-app-insights] Migrate DateResolverDialog class
  samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/DateResolverDialog.java
Labels: PR: reviewed approved

#159 [Samples][21.corebot-app-insights] Migrate DialogBot class
  samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/DialogBot.java
Labels: PR: reviewed approved

#163 [Samples][nlp-with-dispatch] Migrate wwwroot folder
  samples/14.nlp-with-dispatch/src/main/webapp/index.html
Labels: PR: reviewed approved

#162 [Samples][nlp-with-dispatch] Add readme file
  samples/14.nlp-with-dispatch/README.md
Labels: PR: reviewed approved

#164 [Samples][nlp-with-dispatch] Migrate deployment templates folder
  samples/14.nlp-with-dispatch/deploymentTemplates/template-with-new-rg.json
  samples/14.nlp-with-dispatch/deploymentTemplates/template-with-preexisting-rg.json
Labels: PR: reviewed approved

#165 [Samples][nlp-with-dispatch] Migrate cognitiveModels folder
  samples/14.nlp-with-dispatch/cognitiveModels/HomeAutomation.json
  samples/14.nlp-with-dispatch/cognitiveModels/homeautomation.json
  samples/14.nlp-with-dispatch/cognitiveModels/qnamaker.tsv
  samples/14.nlp-with-dispatch/cognitiveModels/weather.json
Labels: PR: reviewed approved

#158 [Samples][Corebot-App-Insights] Add FlightBookingRecognizer class
  samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/FlightBookingRecognizer.java
Labels: PR: reviewed approved

#166 [Samples][nlp-with-dispatch] Add properties in application.properties file
  samples/14.nlp-with-dispatch/src/main/resources/application.properties
Labels: PR: reviewed approved

#168 [Samples][21.corebot-app-insights] Add internal AdapterWithErrorHandler
  samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/AdapterWithErrorHandler.java
Labels: PR: reviewed approved

#161 [Sample 21] Add Application.java
  samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/Application.java
Labels: PR: reviewed approved

#169 [Samples][nlp-with-dispatch] Migrate startup class as Application class
  samples/14.nlp-with-dispatch/src/main/java/com/microsoft/bot/sample/nlp/with/dispatch/Application.java
Labels: PR: reviewed approved

#170 [Samples][nlp-with-dispatch] Migrate BotServices interface
  samples/14.nlp-with-dispatch/src/main/java/com/microsoft/bot/sample/nlp/with/dispatch/BotServices.java
Labels: PR: reviewed approved

#172 [Samples][Corebot-App-Insights] Add package-info + some checkstyle fixes
  samples/21.corebot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/FlightBookingRecognizer.java
  samples/21.corebot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/MainDialog.java
  samples/21.corebot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/package-info.java
Labels: PR: reviewed approved
