Repository southworks/botbuilder-java, pull requests merged in 2021-02, with the labels that each got.

#46 [Bot-Ai-QnA] Apply requested feedback
  libraries/bot-ai-qna/pom.xml
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/IQnAMakerClient.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMaker.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerComponentRegistration.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerOptions.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerRecognizer.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/dialogs/QnAMakerDialog.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/dialogs/package-info.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/RankerTypes.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/package-info.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/package-info.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/schemas/Microsoft.QnAMakerDialog.schema
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/schemas/Microsoft.QnAMakerRecognizer.schema
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/ActiveLearningUtils.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/BindToActivity.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/GenerateAnswerUtils.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/QnACardBuilder.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/QnATelemetryConstants.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/TrainUtils.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/package-info.java
Labels: PR: promoted to microsoft, PR: reviewed approved

#47 [Bot-Ai-QnA][Unit-Tests] Add TestData folder
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_IsTest_True.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_LegacyEndpointAnswer.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_RankerType_QuestionOnly.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_ReturnAnswer_MultiTurnLevel1.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_ReturnAnswer_withPrompts.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_ReturnsAnswer.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_ReturnsAnswerWithContext.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_ReturnsAnswerWithIntent.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_ReturnsAnswerWithoutContext.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_ReturnsAnswer_GivenScoreThresholdQueryOption.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_ReturnsAnswer_WhenNoAnswerFoundInKb.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_ReturnsAnswersWithMetadataBoost.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_ReturnsNoAnswer.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_TestThreshold.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_TopNAnswer.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_TopNAnswer_DisableActiveLearning.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/QnaMaker_UsesStrictFilters_ToReturnAnswer.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/TestData/qnamaker.settings.development.westus.json
Labels: PR: reviewed approved

#48 [QnA] Add QnAMakerTraceInfoTests
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/QnAMakerTraceInfoTests.java
Labels: PR: reviewed approved

#49 [QnA] Add MyTurnContext class
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/MyTurnContext.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_IsTest_True.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_LegacyEndpointAnswer.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_RankerType_QuestionOnly.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_ReturnAnswer_MultiTurnLevel1.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_ReturnAnswer_withPrompts.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_ReturnsAnswer.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_ReturnsAnswerWithContext.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_ReturnsAnswerWithIntent.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_ReturnsAnswerWithoutContext.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_ReturnsAnswer_GivenScoreThresholdQueryOption.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_ReturnsAnswer_WhenNoAnswerFoundInKb.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_ReturnsAnswersWithMetadataBoost.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_ReturnsNoAnswer.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_TestThreshold.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_TopNAnswer.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_TopNAnswer_DisableActiveLearning.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/QnaMaker_UsesStrictFilters_ToReturnAnswer.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/TestData/qnamaker.settings.development.westus.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/dialogs/QnAMakerDialogTest.java
Labels: PR: review wanted

#50 Internal/southworks/library/bot ai qna/unit tests qn a maker card equality comparer
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerCardEqualityComparer.java
Labels: PR: reviewed approved

#51 [QnA] Add QnAMakerTest class
  libraries/bot-ai-qna/pom.xml
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTests.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/dialogs/QnAMakerDialogTest.java
  pom.xml
Labels: PR: review wanted

#52 [QnA] Add Unit Tests
  libraries/bot-ai-qna/pom.xml
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/dialogs/QnAMakerDialogTest.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/MyTurnContext.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerCardEqualityComparer.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTests.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTraceInfoTests.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_IsTest_True.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_LegacyEndpointAnswer.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_RankerType_QuestionOnly.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_ReturnAnswer_MultiTurnLevel1.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_ReturnAnswer_withPrompts.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_ReturnsAnswer.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_ReturnsAnswerWithContext.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_ReturnsAnswerWithIntent.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_ReturnsAnswerWithoutContext.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_ReturnsAnswer_GivenScoreThresholdQueryOption.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_ReturnsAnswer_WhenNoAnswerFoundInKb.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_ReturnsAnswersWithMetadataBoost.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_ReturnsNoAnswer.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_TestThreshold.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_TopNAnswer.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_TopNAnswer_DisableActiveLearning.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_UsesStrictFilters_ToReturnAnswer.json
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/qnamaker.settings.development.westus.json
  pom.xml
Labels: PR: reviewed approved

#53 [QnA] Add QnAMakerRecognizer, QnAMakerRecognizerTests and fix issues
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerOptions.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerRecognizer.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/HttpRequestUtils.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerRecognizerTests.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTests.java
Labels: PR: review wanted

#54 [QnA] Fix QnAMakerRecognizerTests unit tests
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMaker.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerRecognizer.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/GenerateAnswerUtils.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/HttpRequestUtils.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerRecognizerTests.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTests.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTraceInfoTests.java
  libraries/bot-builder/src/test/java/com/microsoft/bot/builder/adapters/TestAdapter.java
Labels: PR: reviewed approved

#56 [QnA] Fix QnA unit tests
  libraries/bot-ai-qna/pom.xml
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMaker.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerRecognizer.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/GenerateAnswerUtils.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/HttpRequestUtils.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerRecognizerTests.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTests.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTraceInfoTests.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_ReturnsAnswer_GivenScoreThresholdQueryOption.json
Labels: PR: reviewed approved

#55 [Samples][11.qnamaker] Add project structure
  samples/11.qnamaker/LICENSE
  samples/11.qnamaker/README.md
  samples/11.qnamaker/deploymentTemplates/template-with-new-rg.json
  samples/11.qnamaker/deploymentTemplates/template-with-preexisting-rg.json
  samples/11.qnamaker/src/main/java/com/microsoft/bot/sample/qnamaker/Application.java
  samples/11.qnamaker/src/test/java/com/microsoft/bot/sample/qnamaker/ApplicationTest.java
Labels: PR: reviewed approved

#57 [QnA] Fix QnA Unit Tests
  libraries/bot-ai-qna/pom.xml
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMaker.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerRecognizer.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/GenerateAnswerUtils.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/HttpRequestUtils.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerRecognizerTests.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTests.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTraceInfoTests.java
  libraries/bot-builder/src/test/java/com/microsoft/bot/builder/adapters/TestAdapter.java
Labels: PR: reviewed approved

#59 [Samples][11.qnamaker] Add deploymentTemplates folder
  samples/11.qnamaker/deploymentTemplates/new-rg-parameters.json
  samples/11.qnamaker/deploymentTemplates/preexisting-rg-parameters.json
  samples/11.qnamaker/deploymentTemplates/template-with-new-rg.json
  samples/11.qnamaker/deploymentTemplates/template-with-preexisting-rg.json
Labels: PR: reviewed approved

#60 [Samples][11.qnamaker] Add webapp folder
  samples/11.qnamaker/src/main/webapp/META-INF/MANIFEST.MF
  samples/11.qnamaker/src/main/webapp/WEB-INF/web.xml
  samples/11.qnamaker/src/main/webapp/index.html
Labels: PR: reviewed approved

#64 [Samples][11.qnamaker] Add application.properties
  samples/11.qnamaker/src/main/resources/application.properties
  samples/11.qnamaker/src/main/resources/log4j2.json
Labels: PR: reviewed approved

#61 [Samples][11.qnamaker] Add qnabot class
  samples/11.qnamaker/pom.xml
  samples/11.qnamaker/src/main/java/com/microsoft/bot/sample/qnamaker/QnABot.java
Labels: PR: reviewed approved

#62 [Bot-Azure] Update CosmosDbKeyEscape
  libraries/bot-azure/src/main/java/com/microsoft/bot/azure/CosmosDbKeyEscape.java
Labels: PR: reviewed approved

#63 [Bot-Azure] Update CosmosDbPartitionedStorageOptions
  libraries/bot-azure/src/main/java/com/microsoft/bot/azure/CosmosDbPartitionedStorageOptions.java
Labels: PR: reviewed approved

#58 [Samples][11.qnamaker] Add Application class
  samples/11.qnamaker/src/main/java/com/microsoft/bot/sample/qnamaker/Application.java
Labels: PR: reviewed approved

#67 [QnA] Apply requested feedback
  etc/bot-checkstyle.xml
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMaker.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerClient.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerRecognizer.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/TelemetryQnAMaker.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/dialogs/QnAMakerDialog.java
  libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/resources/icon.png
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerCardEqualityComparer.java
  libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTests.java
Labels: PR: reviewed approved

#65 [Samples][11.qnamaker] Add README
  samples/11.qnamaker/README.md
Labels: PR: reviewed approved

#66 [Bot Azure] Update CosmosDBKeyEscapeTests
  libraries/bot-azure/src/test/java/com/microsoft/bot/azure/CosmosDBKeyEscapeTests.java
Labels: PR: reviewed approved

#69 [Bot Azure] Update CosmosDbPartitionStorageTests
  libraries/bot-azure/src/test/java/com/microsoft/bot/azure/CosmosDbPartitionStorageTests.java
Labels: PR: reviewed approved

#72 [Bot Azure] Fix tests
  libraries/bot-azure/src/main/java/com/microsoft/bot/azure/CosmosDbKeyEscape.java
  libraries/bot-azure/src/main/java/com/microsoft/bot/azure/CosmosDbPartitionedStorage.java
Labels: PR: review wanted

#73 [Samples][13.core-bot] Add project structure
  samples/13.core-bot/LICENSE
  samples/13.core-bot/README.md
  samples/13.core-bot/deploymentTemplates/template-with-new-rg.json
  samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/Application.java
  samples/13.core-bot/src/test/java/com/microsoft/bot/sample/core/ApplicationTest.java
Labels: PR: reviewed approved

#75 [Samples][13.core-bot] Add Application.java class
  samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/Application.java
Labels: PR: review wanted

#76 Add changes requested from PR 1023
  samples/11.qnamaker/deploymentTemplates/new-rg-parameters.json
  samples/11.qnamaker/deploymentTemplates/preexisting-rg-parameters.json
  samples/11.qnamaker/deploymentTemplates/template-with-new-rg.json
  samples/11.qnamaker/deploymentTemplates/template-with-preexisting-rg.json
  samples/11.qnamaker/src/main/java/com/microsoft/bot/sample/qnamaker/QnABot.java
Labels: PR: reviewed approved

#77 Add Application.properties
  samples/13.core-bot/src/main/resources/application.properties
  samples/13.core-bot/src/main/resources/log4j2.json
Labels: PR: reviewed approved
