Repository southworks/botbuilder-java, pull requests merged in 2021-04, with the labels that each got.

#173 [Samples][40.timex-resolution] Create main structure
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Application.java
  samples/40.timex-resolution/src/main/resources/application.properties
  samples/40.timex-resolution/src/main/webapp/index.html
  samples/40.timex-resolution/src/pom.xml
  samples/40.timex-resolution/src/test/java/com/microsoft/bot/sample/timex/resolution/ApplicationTest.java
Labels: PR: review wanted

#174 [Samples][42.scaleout] Add main structure + README + Store interface
  samples/42.scaleout/LICENSE
  samples/42.scaleout/README.md
  samples/42.scaleout/pom.xml
  samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/Store.java
  samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/package-info.java
  samples/42.scaleout/src/main/resources/application.properties
  samples/42.scaleout/src/main/resources/log4j2.json
  samples/42.scaleout/src/main/webapp/META-INF/MANIFEST.MF
  samples/42.scaleout/src/main/webapp/WEB-INF/web.xml
  samples/42.scaleout/src/main/webapp/index.html
  samples/42.scaleout/src/test/java/com/microsoft/bot/sample/scaleout/ApplicationTest.java
Labels: PR: review wanted

#175 [Samples][42.scaleout] Add RootDialog
  samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/RootDialog.java
Labels: PR: reviewed approved

#176 [Samples][42.scaleout] Add DialogHostAdapter class
  samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/DialogHostAdapter.java
Labels: PR: reviewed approved

#179 [Samples][42.scaleout] Add RefAccessor class
  samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/RefAccessor.java
Labels: PR: reviewed approved

#180 [Samples][42.scaleout] Add DialogHost and change of Object to JsonNode
  samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/DialogHost.java
  samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/Store.java
Labels: PR: reviewed approved

#178 [Samples][40.timex-resolution] Migrate Parsing class and fix pom
  samples/40.timex-resolution/pom.xml
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Parsing.java
Labels: PR: reviewed approved

#181 [Samples][Timex-Resolution] Add Constraints class
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Constraints.java
Labels: PR: reviewed approved

#177 [Samples][42.scaleout] Add ScaleoutBot class
  samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/ScaleoutBot.java
Labels: PR: reviewed approved

#182 [Samples][42.scaleout] Add MemoryStore class
  samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/MemoryStore.java
Labels: PR: reviewed approved

#184 [Samples][Timex-Resolution] Add Program class
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Application.java
Labels: PR: reviewed approved

#185 Migrate Ambiguity class
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Ambiguity.java
Labels: PR: reviewed approved

#188 [Samples][Timex Resolution] Add Ranges class
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Ranges.java
Labels: PR: reviewed approved

#183 [Samples][42.scaleout] Add BlobStore class
  samples/42.scaleout/pom.xml
  samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/BlobStore.java
Labels: PR: reviewed approved

#186 [Samples][42.scaleout] Add Application class
  samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/Application.java
Labels: PR: reviewed approved

#190 [Samples][timex-resolution] Add Resolutions class
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Application.java
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Resolutions.java
Labels: PR: reviewed approved

#191 [Samples][40.timex-resolution] Migrate LanguageGeneration class
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/LanguageGeneration.java
Labels: PR: reviewed approved

#192 [Samples][40.timex-resolution] Migrate README document
  samples/40.timex-resolution/README.md
Labels: PR: changes requested

#193 Fixes against C# version
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Ambiguity.java
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Application.java
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Constraints.java
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/LanguageGeneration.java
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Parsing.java
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Ranges.java
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Resolutions.java
  samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/package-info.java
  samples/40.timex-resolution/src/main/resources/application.properties
  samples/40.timex-resolution/src/main/webapp/index.html
Labels: PR: reviewed approved
